# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('pageviews_timesTwo', PACKAGE = 'pageviews', x)
}

#'@title normalise IP addresses for geolocation
#'@description \code{normalise_ips} takes IP addresses and x_forwarded_for
#'values and, in the event that x_forwarded_for is non-null, attempts to
#'extract the "real" IP closest to the client.
#'
#'@param ip_addresses a vector of IP addresses
#'
#'@param x_forwarded_fors an equally-sized vector of XFF values, retrieved
#'from \code{\link{read_sampled_log}}.
#'
#'@return a vector of IP addresses, incorporating the XFF header value
#'where appropriate
#'
#'@export
normalise_ips <- function(ip_addresses, x_forwarded_fors) {
    .Call('pageviews_normalise_ips', PACKAGE = 'pageviews', ip_addresses, x_forwarded_fors)
}

